name: Update JSON and redeploy

on:
  schedule:
    - cron: "0 */5 * * *"   # cada 5 horas (UTC)
  workflow_dispatch:         # permite lanzarlo manualmente desde Actions

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, skipping dependencies"
          fi

      - name: Run update script
        run: python tablaLaliga/Clasificacion-laliga.py   # üî• CAMBIO AQU√ç
        working-directory: tablaLaliga  # ‚úÖ Ejecuta desde la carpeta tablaLaliga

      - name: Commit changes
        run: |
          git config user.name "JuanjoCV04"
          git config user.email "juanjocaval@gmail.com"
          git add .
          git commit -m "Auto update clasificacion_laliga.json [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Trigger Vercel Deploy Hook
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_KrAGHIs6trOY5HQkvUwm0h9t3Zbk/nIqYE9IjX8